language: elixir
elixir:
  - 1.6.1
otp_release:
  - 20.2
matrix:
  include:
  - otp_release: 19.3
    elixir: 1.5.3
env:
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mat@geeky.net
